### Editor authenticate. Use the token from this as the bearer token below
POST http://localhost:5000/users/Authenticate
Content-Type: application/json

{
  "Email" : "editor@example.org",
  "Password" : "password"
}

### Admin authenticate
POST http://localhost:5000/users/Authenticate
Content-Type: application/json

{
  "Email" : "admin@example.org",
  "Password" : "password"
}

### This request requires the Editors policy
POST http://localhost:5000/pages/Add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImVkaXRvckBleGFtcGxlLm9yZyIsInJvbGUiOiJFZGl0b3IiLCJuYmYiOjE1NDM4NTI5MjgsImV4cCI6MTU0NDQ1NzcyOCwiaWF0IjoxNTQzODUyOTI4fQ.qMUR6DsLp17WBPqYn6S2hqrpOXPDKF8mI-2RRV6z7VI

{
  "title": "my new page",
  "createdBy": "editor",
  "isLocked": false
}

### This request requires the Admins policy
GET http://localhost:5000/users/GetAll
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluQGV4YW1wbGUub3JnIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNTQzODU1MTQ5LCJleHAiOjE1NDQ0NTk5NDksImlhdCI6MTU0Mzg1NTE0OX0.DNDjVxtVsFSaEhaUF6jB7rZ0vuXtt1fz8dR6aUddLYY

### These requests needs no authentication
GET http://localhost:5000/pages/Get?id=1
Accept: */*

###
GET http://localhost:5000/pages/AllPages
Accept: */*

###